network:
  version: 2
  ethernets:
    enp0s3:  # already using for Private-DMZ
      dhcp4: no
      addresses: [192.168.20.10/24]
    enp0s8:  # new adapter for Public-DMZ
      dhcp4: no
      addresses: [192.168.10.100/24]
